partePele = {
  "camisa" = "pele",
  "perna" = "pernaparte", 
  "sapato" = "pe",
}

defaultClothes = {
  {["camisa"] = {1,1},["perna"] = {1,1},["sapato"]= {1,1},["mascara"] = {0,1},["oculos"] = {0,1},["mochila"] = {0,1},["cabelo"] = {0,1},["pele"] = {1,1},["face"] = {1,1},["pe"] = {1,1},["pernaparte"] = {1,1}},
  }

roupas = { 
	[7]--[[Numero da skin]]-- = {-- [parte da roupa] = {"nome da parte da roupa na skin."}
		["camisa"] = {"jbib_diff_016_w_uni","jbib_diff_007_x_uni","casaco"},
		["perna"] = {"Cueca","perna2","lowr_diff_001_a_whi"},
		["sapato"] = {"sandalia","tubarao","feet_diff_003_d_uni","tenis"},
		["cabelo"] = {"cabelo2","cabelo3","cabelo6","cabelo1","cabelo","bone"},
		["oculos"] = {"oculos1","oculos"},
		["mochila"] = {"mochila"},
		["mascara"] = {"mascaratxd","berd_diff_016_h_uni"},
		["face"] = {"Rosto","Rosto","Rosto"},
		["pele"] = {"Body","Body","Body"},
		["pernaparte"] = {"Perna","Perna","Perna"},
		["pe"] = {"Pe","Pe","Pe"},
	},
	[10] = {
		["cabelo"] = {"hair_diff_011_c_uni","cabelo2","hair_diff_000_b_uni"},
		["camisa"] = {"jbib_diff_002_k_uni","Ftop3","Ftop2","jbib_diff_004_r_uni"},
		["perna"] = {"calcinha","Fshort","fcalca"},
		["sapato"] = {"sandalia","tubarao","feet_diff_003_d_uni"},
		["oculos"] = {"oculos1","oculos3"},
		["mascara"] = {"mascaratxd","berd_diff_016_h_uni"},
		["mochila"] = {"mochila"},
		["face"] = {"head_diff_014_a_whi","head_diff_014_a_whi","head_diff_014_a_whi"},
		["pele"] = {"uppr_diff_015_a_whi","uppr_diff_015_a_whi","uppr_diff_015_a_whi"},
		["pernaparte"] = {"perna","perna","perna"},
		["pe"] = {"pe","pe","pe"},
	},
}


-- caminhos dos arquivos de textura.
Textures = {	
	[7] = {
		["cabelo"] = {
			[1] = {
				[1] = "arquivos/7/cabelo/cabelo1/1.png",
				[2] = "arquivos/7/cabelo/cabelo1/2.png",
				[3] = "arquivos/7/cabelo/cabelo1/3.png",
				[4] = "arquivos/7/cabelo/cabelo1/4.png",
			},
			[2] = {
				[1] = "arquivos/7/cabelo/cabelo2/1.png",
				[2] = "arquivos/7/cabelo/cabelo2/2.png",
				[3] = "arquivos/7/cabelo/cabelo2/3.png",
				[4] = "arquivos/7/cabelo/cabelo2/4.png",
				[5] = "arquivos/7/cabelo/cabelo2/5.png",
			},
			[3] = {
				[1] = "arquivos/7/cabelo/cabelo3/1.png",
				[2] = "arquivos/7/cabelo/cabelo3/2.png",
				[3] = "arquivos/7/cabelo/cabelo3/3.png",
				[4] = "arquivos/7/cabelo/cabelo3/4.png",
			},
			[4] = {
				[1] = "arquivos/7/cabelo/cabelo4/1.png",
				[2] = "arquivos/7/cabelo/cabelo4/2.png",
				[3] = "arquivos/7/cabelo/cabelo4/3.png",
				[4] = "arquivos/7/cabelo/cabelo4/4.png",
				[5] = "arquivos/7/cabelo/cabelo4/5.png",
				[6] = "arquivos/7/cabelo/cabelo4/6.png",
			},
			[5] = {
				[1] = "arquivos/7/cabelo/chapeu.pescador/1.png",
				[2] = "arquivos/7/cabelo/chapeu.pescador/2.png",
				[3] = "arquivos/7/cabelo/chapeu.pescador/3.png",
				[4] = "arquivos/7/cabelo/chapeu.pescador/4.png",
				[5] = "arquivos/7/cabelo/chapeu.pescador/5.png",
			},
			[6] = {
				[1] = "arquivos/7/cabelo/bone/1.png",
				[2] = "arquivos/7/cabelo/bone/2.png",
				[3] = "arquivos/7/cabelo/bone/3.png",
				[4] = "arquivos/7/cabelo/bone/4.png",
				[5] = "arquivos/7/cabelo/bone/5.png",
				[6] = "arquivos/7/cabelo/bone/6.png",
				[7] = "arquivos/7/cabelo/bone/7.png",
			},
		},
		["camisa"] = {
			[1] = {
				[1] = "arquivos/7/camisa/camisa1/1.png",
				[2] = "arquivos/7/camisa/camisa1/2.png",
				[3] = "arquivos/7/camisa/camisa1/3.png",
				[4] = "arquivos/7/camisa/camisa1/4.png",
				[5] = "arquivos/7/camisa/camisa1/5.png",
				[6] = "arquivos/7/camisa/camisa1/6.png",
				[7] = "arquivos/7/camisa/camisa1/7.png",
				[8] = "arquivos/7/camisa/camisa1/8.png",
			},
			[2] = {
				[1] = "arquivos/7/camisa/camisa2/1.png",
				[2] = "arquivos/7/camisa/camisa2/2.png",
				[3] = "arquivos/7/camisa/camisa2/3.png",
				[4] = "arquivos/7/camisa/camisa2/4.png",
				[5] = "arquivos/7/camisa/camisa2/5.png",
				[6] = "arquivos/7/camisa/camisa2/6.png",
				[7] = "arquivos/7/camisa/camisa2/7.png",
				[8] = "arquivos/7/camisa/camisa2/8.png",
				[9] = "arquivos/7/camisa/camisa2/9.png",
				[10] = "arquivos/7/camisa/camisa2/10.png",
				[11] = "arquivos/7/camisa/camisa2/11.png",
				[12] = "arquivos/7/camisa/camisa2/12.png",
				[13] = "arquivos/7/camisa/camisa2/13.png",
				[14] = "arquivos/7/camisa/camisa2/14.png",
				[15] = "arquivos/7/camisa/camisa2/15.png",
				[16] = "arquivos/7/camisa/camisa2/16.png",
				[17] = "arquivos/7/camisa/camisa2/17.png",
				[18] = "arquivos/7/camisa/camisa2/18.png",
				[19] = "arquivos/7/camisa/camisa2/19.png",
				[20] = "arquivos/7/camisa/camisa2/20.png",
				[21] = "arquivos/7/camisa/camisa2/21.png",
				[22] = "arquivos/7/camisa/camisa2/22.png",
				[23] = "arquivos/7/camisa/camisa2/23.png",
				[24] = "arquivos/7/camisa/camisa2/24.png",
				[25] = "arquivos/7/camisa/camisa2/25.png",
				[26] = "arquivos/7/camisa/camisa2/26.png",
				[27] = "arquivos/7/camisa/camisa2/27.png",
				[28] = "arquivos/7/camisa/camisa2/28.png",
				[29] = "arquivos/7/camisa/camisa2/29.png",
				[30] = "arquivos/7/camisa/camisa2/30.png",
				[31] = "arquivos/7/camisa/camisa2/31.png",
				[32] = "arquivos/7/camisa/camisa2/32.png",
				[33] = "arquivos/7/camisa/camisa2/33.png",
				[34] = "arquivos/7/camisa/camisa2/34.png",
				[35] = "arquivos/7/camisa/camisa2/35.png",
				[36] = "arquivos/7/camisa/camisa2/36.png",
				[37] = "arquivos/7/camisa/camisa2/37.png",
				[38] = "arquivos/7/camisa/camisa2/38.png",
				[39] = "arquivos/7/camisa/camisa2/39.png",
				[40] = "arquivos/7/camisa/camisa2/40.png",
				--[[[41] = "arquivos/7/camisa/camisa2/41.png",
				[42] = "arquivos/7/camisa/camisa2/42.png",
				[43] = "arquivos/7/camisa/camisa2/43.png",
				[44] = "arquivos/7/camisa/camisa2/44.png",
				[45] = "arquivos/7/camisa/camisa2/45.png",
				[46] = "arquivos/7/camisa/camisa2/46.png",
				[47] = "arquivos/7/camisa/camisa2/47.png",
				[48] = "arquivos/7/camisa/camisa2/48.png",
				[49] = "arquivos/7/camisa/camisa2/49.png",
				[50] = "arquivos/7/camisa/camisa2/50.png",
				[51] = "arquivos/7/camisa/camisa2/51.png",--]]
			},
			[3] = {
				[1] = "arquivos/PartesComum/camisa/casaco/1.png",
				[2] = "arquivos/PartesComum/camisa/casaco/2.png",
				[3] = "arquivos/PartesComum/camisa/casaco/3.png",
				[4] = "arquivos/PartesComum/camisa/casaco/4.png",
				[5] = "arquivos/PartesComum/camisa/casaco/5.png",
				[6] = "arquivos/PartesComum/camisa/casaco/6.png",
				[7] = "arquivos/PartesComum/camisa/casaco/7.png",
				[8] = "arquivos/PartesComum/camisa/casaco/8.png",	
				[9] = "arquivos/PartesComum/camisa/casaco/9.png",
				[10] = "arquivos/PartesComum/camisa/casaco/10.png",
				[11] = "arquivos/PartesComum/camisa/casaco/11.png",
				[12] = "arquivos/PartesComum/camisa/casaco/12.png",
				[13] = "arquivos/PartesComum/camisa/casaco/13.png",
				[14] = "arquivos/PartesComum/camisa/casaco/14.png",
				[15] = "arquivos/PartesComum/camisa/casaco/15.png",
				[16] = "arquivos/PartesComum/camisa/casaco/16.png",	
				[17] = "arquivos/PartesComum/camisa/casaco/17.png",
				[18] = "arquivos/PartesComum/camisa/casaco/18.png",
				[19] = "arquivos/PartesComum/camisa/casaco/19.png",
				[20] = "arquivos/PartesComum/camisa/casaco/20.png",
			},
		},
		["perna"] = {
			[1] = {
				[1] = "arquivos/7/perna/cueca/1.png",
				[2] = "arquivos/7/perna/cueca/2.png",
				[3] = "arquivos/7/perna/cueca/3.png",
				[4] = "arquivos/7/perna/cueca/4.png",
				[5] = "arquivos/7/perna/cueca/5.png",
			},
			[2] = {
				[1] = "arquivos/7/perna/short/1.png",
				[2] = "arquivos/7/perna/short/2.png",
				[3] = "arquivos/7/perna/short/3.png",
				[4] = "arquivos/7/perna/short/4.png",
				[5] = "arquivos/7/perna/short/5.png",
				[6] = "arquivos/7/perna/short/6.png",
				[7] = "arquivos/7/perna/short/7.png",
				[8] = "arquivos/7/perna/short/8.png",
				[9] = "arquivos/7/perna/short/9.png",
				[10] = "arquivos/7/perna/short/10.png",
				[11] = "arquivos/7/perna/short/11.png",
				[12] = "arquivos/7/perna/short/12.png",
				[13] = "arquivos/7/perna/short/13.png",
				[14] = "arquivos/7/perna/short/14.png",
				[15] = "arquivos/7/perna/short/15.png",
				[16] = "arquivos/7/perna/short/16.png",
				[17] = "arquivos/7/perna/short/17.png",
				[18] = "arquivos/7/perna/short/18.png",
				[19] = "arquivos/7/perna/short/19.png",
			},
			[3] = {
				[1] = "arquivos/PartesComum/perna/calca/1.png",	
				[2] = "arquivos/PartesComum/perna/calca/2.png",
				[3] = "arquivos/PartesComum/perna/calca/3.png",
				[4] = "arquivos/PartesComum/perna/calca/4.png",
				[5] = "arquivos/PartesComum/perna/calca/5.png",
				[6] = "arquivos/PartesComum/perna/calca/6.png",	
				[7] = "arquivos/PartesComum/perna/calca/7.png",
				[8] = "arquivos/PartesComum/perna/calca/8.png",
				[9] = "arquivos/PartesComum/perna/calca/9.png",
				[10] = "arquivos/PartesComum/perna/calca/10.png",
				[11] = "arquivos/PartesComum/perna/calca/11.png",	
				[12] = "arquivos/PartesComum/perna/calca/12.png",	
			},
		},
		["sapato"] = {
			[1] = {
				[1] = "arquivos/PartesComum/sapato/sandalia/1.png",
				[2] = "arquivos/PartesComum/sapato/sandalia/2.png",
				[3] = "arquivos/PartesComum/sapato/sandalia/3.png",
				[4] = "arquivos/PartesComum/sapato/sandalia/4.png",
				[5] = "arquivos/PartesComum/sapato/sandalia/5.png",
				[6] = "arquivos/PartesComum/sapato/sandalia/6.png",
				[7] = "arquivos/PartesComum/sapato/sandalia/7.png",
				[8] = "arquivos/PartesComum/sapato/sandalia/8.png",
				[9] = "arquivos/PartesComum/sapato/sandalia/9.png",
			},
			[2] = {
				[1] = "arquivos/PartesComum/sapato/tubarao/1.png",
				[2] = "arquivos/PartesComum/sapato/tubarao/2.png",
				[3] = "arquivos/PartesComum/sapato/tubarao/3.png",
				[4] = "arquivos/PartesComum/sapato/tubarao/4.png",
				[5] = "arquivos/PartesComum/sapato/tubarao/5.png",
				[6] = "arquivos/PartesComum/sapato/tubarao/6.png",
			},
			[3] = {
				[1] = "arquivos/PartesComum/sapato/allStar/1.png",
				[2] = "arquivos/PartesComum/sapato/allStar/2.png",
				[3] = "arquivos/PartesComum/sapato/allStar/3.png",
				[4] = "arquivos/PartesComum/sapato/allStar/4.png",
				[5] = "arquivos/PartesComum/sapato/allStar/5.png",
				[6] = "arquivos/PartesComum/sapato/allStar/6.png",
				[7] = "arquivos/PartesComum/sapato/allStar/7.png",
				[8] = "arquivos/PartesComum/sapato/allStar/8.png",
				[9] = "arquivos/PartesComum/sapato/allStar/9.png",
			},
			[4] = {
				[1] = "arquivos/7/sapato/tenis/1.png",
				[2] = "arquivos/7/sapato/tenis/2.png",
				[3] = "arquivos/7/sapato/tenis/3.png",
				[4] = "arquivos/7/sapato/tenis/4.png",
				[5] = "arquivos/7/sapato/tenis/5.png",
				[6] = "arquivos/7/sapato/tenis/6.png",
				[7] = "arquivos/7/sapato/tenis/7.png",
				[8] = "arquivos/7/sapato/tenis/8.png",
				[9] = "arquivos/7/sapato/tenis/9.png",
			},
		},
		["oculos"] = {
			[1] = {
				[1] = "arquivos/PartesComum/oculos/xsquared/1.png",
				[2] = "arquivos/PartesComum/oculos/xsquared/2.png",
				[3] = "arquivos/PartesComum/oculos/xsquared/3.png",
				[4] = "arquivos/PartesComum/oculos/xsquared/4.png",
				[5] = "arquivos/PartesComum/oculos/xsquared/5.png",
				[6] = "arquivos/PartesComum/oculos/xsquared/6.png",
				[7] = "arquivos/PartesComum/oculos/xsquared/7.png",
				[8] = "arquivos/PartesComum/oculos/xsquared/8.png",
			},
			[2] = {
				[1] = "arquivos/PartesComum/oculos/juju/1.png",
				[2] = "arquivos/PartesComum/oculos/juju/2.png",
				[3] = "arquivos/PartesComum/oculos/juju/3.png",
				[4] = "arquivos/PartesComum/oculos/juju/4.png",
				[5] = "arquivos/PartesComum/oculos/juju/5.png",
				[6] = "arquivos/PartesComum/oculos/juju/6.png",
				[7] = "arquivos/PartesComum/oculos/juju/7.png",
				[8] = "arquivos/PartesComum/oculos/juju/8.png",
			},
		},
		["mochila"] = {
			[1] = {
				[1] = "arquivos/PartesComum/mochila/paraquedas/1.png",
				[2] = "arquivos/PartesComum/mochila/paraquedas/2.png",
				[3] = "arquivos/PartesComum/mochila/paraquedas/3.png",
				[4] = "arquivos/PartesComum/mochila/paraquedas/4.png",
				[5] = "arquivos/PartesComum/mochila/paraquedas/5.png",
				[6] = "arquivos/PartesComum/mochila/paraquedas/6.png",
				[7] = "arquivos/PartesComum/mochila/paraquedas/7.png",
				[8] = "arquivos/PartesComum/mochila/paraquedas/8.png",
				[9] = "arquivos/PartesComum/mochila/paraquedas/9.png",
				[10] = "arquivos/PartesComum/mochila/paraquedas/10.png",
				[11] = "arquivos/PartesComum/mochila/paraquedas/11.png",
				[12] = "arquivos/PartesComum/mochila/paraquedas/12.png",
				[13] = "arquivos/PartesComum/mochila/paraquedas/13.png",
				[14] = "arquivos/PartesComum/mochila/paraquedas/14.png",
			},
		},
		["mascara"] = {			
			[1] = {
				[1] = "arquivos/PartesComum/mascara/padrao/1.png",
				[2] = "arquivos/PartesComum/mascara/padrao/2.png",
				[3] = "arquivos/PartesComum/mascara/padrao/3.png",
				[4] = "arquivos/PartesComum/mascara/padrao/4.png",
				[5] = "arquivos/PartesComum/mascara/padrao/5.png",
				[6] = "arquivos/PartesComum/mascara/padrao/6.png",
				[7] = "arquivos/PartesComum/mascara/padrao/7.png",
				[8] = "arquivos/PartesComum/mascara/padrao/8.png",
				[9] = "arquivos/PartesComum/mascara/padrao/9.png",
			},
			[2] = {
				[1] = "arquivos/PartesComum/mascara/bandana/1.png",
				[2] = "arquivos/PartesComum/mascara/bandana/2.png",
				[3] = "arquivos/PartesComum/mascara/bandana/3.png",
				[4] = "arquivos/PartesComum/mascara/bandana/4.png",
				[5] = "arquivos/PartesComum/mascara/bandana/5.png",
				[6] = "arquivos/PartesComum/mascara/bandana/6.png",
				[7] = "arquivos/PartesComum/mascara/bandana/7.png",
				[8] = "arquivos/PartesComum/mascara/bandana/8.png",
				[9] = "arquivos/PartesComum/mascara/bandana/9.png",
			},
		},
		["pernaparte"] = {			
			[1] = {
				[0] = "arquivos/7/texturaPele/perna/1/padrao.png",
				[1] = "arquivos/7/texturaPele/perna/1/padrao.png",
				[2] = "arquivos/7/texturaPele/perna/1/short.png",
				[3] = "arquivos/7/texturaPele/perna/1/calca.png",
			},
			[2] = {
				[0] = "arquivos/7/texturaPele/perna/2/padrao.png",
				[1] = "arquivos/7/texturaPele/perna/2/padrao.png",
				[2] = "arquivos/7/texturaPele/perna/2/short.png",
				[3] = "arquivos/7/texturaPele/perna/2/calca.png",
			},
			[3] = {
				[0] = "arquivos/7/texturaPele/perna/3/padrao.png",
				[1] = "arquivos/7/texturaPele/perna/3/padrao.png",
				[2] = "arquivos/7/texturaPele/perna/3/short.png",
				[3] = "arquivos/7/texturaPele/perna/3/calca.png",
			},
		},
		["pele"] = {			
			[1] = {
				[0] = "arquivos/7/texturaPele/corpo/1/padrao.png",
				[1] = "arquivos/7/texturaPele/corpo/1/camisa1.png",
				[2] = "arquivos/7/texturaPele/corpo/1/camisa2.png",
				[3] = "arquivos/7/texturaPele/corpo/1/casaco.png",
				[4] = "arquivos/7/texturaPele/corpo/1/casaco.png",
			},
			[2] = {
				[0] = "arquivos/7/texturaPele/corpo/2/padrao.png",
				[1] = "arquivos/7/texturaPele/corpo/2/camisa1.png",
				[2] = "arquivos/7/texturaPele/corpo/2/camisa2.png",
				[3] = "arquivos/7/texturaPele/corpo/2/casaco.png",
				[4] = "arquivos/7/texturaPele/corpo/2/casaco.png",
			},
			[3] = {
				[0] = "arquivos/7/texturaPele/corpo/3/padrao.png",
				[1] = "arquivos/7/texturaPele/corpo/3/camisa1.png",
				[2] = "arquivos/7/texturaPele/corpo/3/camisa2.png",
				[3] = "arquivos/7/texturaPele/corpo/3/casaco.png",
				[4] = "arquivos/7/texturaPele/corpo/3/casaco.png",
			},
		},
		["face"] = {			
			[1] = {
				[1] = "arquivos/7/texturaPele/face/1/1.png",
				[2] = "arquivos/7/texturaPele/face/1/2.png",
				[3] = "arquivos/7/texturaPele/face/1/3.png",
				[4] = "arquivos/7/texturaPele/face/1/4.png",
				[5] = "arquivos/7/texturaPele/face/1/5.png",
				[6] = "arquivos/7/texturaPele/face/1/6.png",
				[7] = "arquivos/7/texturaPele/face/1/7.png",
				[8] = "arquivos/7/texturaPele/face/1/8.png",
				[9] = "arquivos/7/texturaPele/face/1/9.png",
				[10] = "arquivos/7/texturaPele/face/1/10.png",
			},
			[2] = {
				[1] = "arquivos/7/texturaPele/face/2/1.png",
				[2] = "arquivos/7/texturaPele/face/2/2.png",
				[3] = "arquivos/7/texturaPele/face/2/3.png",
				[4] = "arquivos/7/texturaPele/face/2/4.png",
				[5] = "arquivos/7/texturaPele/face/2/5.png",
				[6] = "arquivos/7/texturaPele/face/2/6.png",
				[7] = "arquivos/7/texturaPele/face/2/7.png",
				[8] = "arquivos/7/texturaPele/face/2/8.png",
				[9] = "arquivos/7/texturaPele/face/2/9.png",
				[10] = "arquivos/7/texturaPele/face/2/10.png",
			},
			[3] = {
				[1] = "arquivos/7/texturaPele/face/3/1.png",
				[2] = "arquivos/7/texturaPele/face/3/2.png",
				[3] = "arquivos/7/texturaPele/face/3/3.png",
				[4] = "arquivos/7/texturaPele/face/3/4.png",
				[5] = "arquivos/7/texturaPele/face/3/5.png",
				[6] = "arquivos/7/texturaPele/face/3/6.png",
				[7] = "arquivos/7/texturaPele/face/3/7.png",
				[8] = "arquivos/7/texturaPele/face/3/8.png",
				[9] = "arquivos/7/texturaPele/face/3/9.png",
				[10] = "arquivos/7/texturaPele/face/3/10.png",

			},
		},
		["pe"] = {			
			[1] = {
				[0] = "arquivos/7/texturaPele/pe/1/padrao.png",
				[1] = "arquivos/7/texturaPele/pe/1/padrao.png",
				[2] = "arquivos/7/texturaPele/pe/1/sem.png",
				[3] = "arquivos/7/texturaPele/pe/1/sem.png",
				[4] = "arquivos/7/texturaPele/pe/1/sem.png",
			},
			[2] = {
				[0] = "arquivos/7/texturaPele/pe/2/padrao.png",
				[1] = "arquivos/7/texturaPele/pe/2/padrao.png",
				[2] = "arquivos/7/texturaPele/pe/1/sem.png",
				[3] = "arquivos/7/texturaPele/pe/1/sem.png",
				[4] = "arquivos/7/texturaPele/pe/1/sem.png",
			},
			[3] = {
				[0] = "arquivos/7/texturaPele/pe/3/padrao.png",
				[1] = "arquivos/7/texturaPele/pe/3/padrao.png",
				[2] = "arquivos/7/texturaPele/pe/1/sem.png",
				[3] = "arquivos/7/texturaPele/pe/1/sem.png",
				[4] = "arquivos/7/texturaPele/pe/1/sem.png",
			},
		},
	},
	[10] = {
		["cabelo"] = {
			[1] = {
				[1] = "arquivos/10/cabelo/cabelo1/1.png",
				[2] = "arquivos/10/cabelo/cabelo1/2.png",
				[3] = "arquivos/10/cabelo/cabelo1/3.png",
				[4] = "arquivos/10/cabelo/cabelo1/4.png",
				[5] = "arquivos/10/cabelo/cabelo1/5.png",
				[6] = "arquivos/10/cabelo/cabelo1/6.png",
				[7] = "arquivos/10/cabelo/cabelo1/7.png",
				[8] = "arquivos/10/cabelo/cabelo1/8.png",
				[9] = "arquivos/10/cabelo/cabelo1/9.png",
			},
			[2] = {
				[1] = "arquivos/10/cabelo/cabelo2/1.png",
				[2] = "arquivos/10/cabelo/cabelo2/2.png",
				[3] = "arquivos/10/cabelo/cabelo2/3.png",
				[4] = "arquivos/10/cabelo/cabelo2/4.png",
				[5] = "arquivos/10/cabelo/cabelo2/5.png",
				[6] = "arquivos/10/cabelo/cabelo2/6.png",
				[7] = "arquivos/10/cabelo/cabelo2/7.png",
				[8] = "arquivos/10/cabelo/cabelo2/8.png",
			},
			[3] = {
				[1] = "arquivos/10/cabelo/cabelo3/1.png",
				[2] = "arquivos/10/cabelo/cabelo3/2.png",
				[3] = "arquivos/10/cabelo/cabelo3/3.png",
				[4] = "arquivos/10/cabelo/cabelo3/4.png",
				[5] = "arquivos/10/cabelo/cabelo3/5.png",
				[6] = "arquivos/10/cabelo/cabelo3/6.png",
				[7] = "arquivos/10/cabelo/cabelo3/7.png",
				[8] = "arquivos/10/cabelo/cabelo3/8.png",
			},
		},
		["camisa"] = {
			[1] = {
				[1] = "arquivos/10/camisa/padrao/1.png",
				[2] = "arquivos/10/camisa/padrao/2.png",
				[3] = "arquivos/10/camisa/padrao/3.png",
				[4] = "arquivos/10/camisa/padrao/4.png",
				[5] = "arquivos/10/camisa/padrao/5.png",
				[6] = "arquivos/10/camisa/padrao/6.png",
				[7] = "arquivos/10/camisa/padrao/7.png",
				[8] = "arquivos/10/camisa/padrao/8.png",
				[9] = "arquivos/10/camisa/padrao/9.png",
				[10] = "arquivos/10/camisa/padrao/10.png",
				[11] = "arquivos/10/camisa/padrao/11.png",
				[12] = "arquivos/10/camisa/padrao/12.png",
				[13] = "arquivos/10/camisa/padrao/13.png",
				[14] = "arquivos/10/camisa/padrao/14.png",
				[15] = "arquivos/10/camisa/padrao/15.png",
				[16] = "arquivos/10/camisa/padrao/16.png",
				[17] = "arquivos/10/camisa/padrao/17.png",
				[18] = "arquivos/10/camisa/padrao/18.png",
				[19] = "arquivos/10/camisa/padrao/19.png",
				[20] = "arquivos/10/camisa/padrao/20.png",
				[21] = "arquivos/10/camisa/padrao/21.png",
				[22] = "arquivos/10/camisa/padrao/22.png",
				[23] = "arquivos/10/camisa/padrao/23.png",
				[24] = "arquivos/10/camisa/padrao/24.png",
				[25] = "arquivos/10/camisa/padrao/25.png",
				[26] = "arquivos/10/camisa/padrao/26.png",
				[27] = "arquivos/10/camisa/padrao/27.png",
				[28] = "arquivos/10/camisa/padrao/28.png",
				[29] = "arquivos/10/camisa/padrao/29.png",
				[30] = "arquivos/10/camisa/padrao/30.png",
				[31] = "arquivos/10/camisa/padrao/31.png",
				[32] = "arquivos/10/camisa/padrao/32.png",
				[33] = "arquivos/10/camisa/padrao/33.png",
				[34] = "arquivos/10/camisa/padrao/34.png",
				[35] = "arquivos/10/camisa/padrao/35.png",
				[36] = "arquivos/10/camisa/padrao/36.png",
				[37] = "arquivos/10/camisa/padrao/37.png",
				[38] = "arquivos/10/camisa/padrao/38.png",
				[39] = "arquivos/10/camisa/padrao/39.png",
				[40] = "arquivos/10/camisa/padrao/40.png",
				[41] = "arquivos/10/camisa/padrao/41.png",
				[42] = "arquivos/10/camisa/padrao/42.png",
				[43] = "arquivos/10/camisa/padrao/43.png",
			},
			[2] = {				
				[1] = "arquivos/10/camisa/padrao/1.png",
				[2] = "arquivos/10/camisa/padrao/2.png",
				[3] = "arquivos/10/camisa/padrao/3.png",
				[4] = "arquivos/10/camisa/padrao/4.png",
				[5] = "arquivos/10/camisa/padrao/5.png",
				[6] = "arquivos/10/camisa/padrao/6.png",
				[7] = "arquivos/10/camisa/padrao/7.png",
				[8] = "arquivos/10/camisa/padrao/8.png",
				[9] = "arquivos/10/camisa/padrao/9.png",
				[10] = "arquivos/10/camisa/padrao/10.png",
				[11] = "arquivos/10/camisa/padrao/11.png",
				[12] = "arquivos/10/camisa/padrao/12.png",
				[13] = "arquivos/10/camisa/padrao/13.png",
				[14] = "arquivos/10/camisa/padrao/14.png",
				[15] = "arquivos/10/camisa/padrao/15.png",
				[16] = "arquivos/10/camisa/padrao/16.png",
				[17] = "arquivos/10/camisa/padrao/17.png",
				[18] = "arquivos/10/camisa/padrao/18.png",
				[19] = "arquivos/10/camisa/padrao/19.png",
				[20] = "arquivos/10/camisa/padrao/20.png",
				[21] = "arquivos/10/camisa/padrao/21.png",
				[22] = "arquivos/10/camisa/padrao/22.png",
				[23] = "arquivos/10/camisa/padrao/23.png",
				[24] = "arquivos/10/camisa/padrao/24.png",
				[25] = "arquivos/10/camisa/padrao/25.png",
				[26] = "arquivos/10/camisa/padrao/26.png",
				[27] = "arquivos/10/camisa/padrao/27.png",
				[28] = "arquivos/10/camisa/padrao/28.png",
				[29] = "arquivos/10/camisa/padrao/29.png",
				[30] = "arquivos/10/camisa/padrao/30.png",
				[31] = "arquivos/10/camisa/padrao/31.png",
				[32] = "arquivos/10/camisa/padrao/32.png",
				[33] = "arquivos/10/camisa/padrao/33.png",
				[34] = "arquivos/10/camisa/padrao/34.png",
				[35] = "arquivos/10/camisa/padrao/35.png",
				[36] = "arquivos/10/camisa/padrao/36.png",
				[37] = "arquivos/10/camisa/padrao/37.png",
				[38] = "arquivos/10/camisa/padrao/38.png",
				[39] = "arquivos/10/camisa/padrao/39.png",
				[40] = "arquivos/10/camisa/padrao/40.png",
				[41] = "arquivos/10/camisa/padrao/41.png",
				[42] = "arquivos/10/camisa/padrao/42.png",
				[43] = "arquivos/10/camisa/padrao/43.png",
				[44] = "arquivos/10/camisa/top3/1.png",
				[45] = "arquivos/10/camisa/top3/2.png",
				[46] = "arquivos/10/camisa/top3/3.png",
				[47] = "arquivos/10/camisa/top3/4.png",
				[48] = "arquivos/10/camisa/top3/5.png",
				[49] = "arquivos/10/camisa/top3/6.png",
				[50] = "arquivos/10/camisa/top3/7.png",
				[51] = "arquivos/10/camisa/top3/8.png",
				[52] = "arquivos/10/camisa/top3/9.png",
				[53] = "arquivos/10/camisa/top3/10.png",
				[54] = "arquivos/10/camisa/top3/11.png",
				[55] = "arquivos/10/camisa/top3/12.png",
				[56] = "arquivos/10/camisa/top3/13.png",
				[57] = "arquivos/10/camisa/top3/14.png",
				[58] = "arquivos/10/camisa/top3/15.png",
				[59] = "arquivos/10/camisa/top3/16.png",
				[60] = "arquivos/10/camisa/top3/17.png",
				[61] = "arquivos/10/camisa/top3/18.png",
				[62] = "arquivos/10/camisa/top3/19.png",
				[63] = "arquivos/10/camisa/top3/20.png",
				[64] = "arquivos/10/camisa/top3/21.png",
				[65] = "arquivos/10/camisa/top3/22.png",
				[66] = "arquivos/10/camisa/top3/23.png",
				[67] = "arquivos/10/camisa/top3/24.png",
			},
			[3] = {				
				[1] = "arquivos/10/camisa/padrao/1.png",
				[2] = "arquivos/10/camisa/padrao/2.png",
				[3] = "arquivos/10/camisa/padrao/3.png",
				[4] = "arquivos/10/camisa/padrao/4.png",
				[5] = "arquivos/10/camisa/padrao/5.png",
				[6] = "arquivos/10/camisa/padrao/6.png",
				[7] = "arquivos/10/camisa/padrao/7.png",
				[8] = "arquivos/10/camisa/padrao/8.png",
				[9] = "arquivos/10/camisa/padrao/9.png",
				[10] = "arquivos/10/camisa/padrao/10.png",
				[11] = "arquivos/10/camisa/padrao/11.png",
				[12] = "arquivos/10/camisa/padrao/12.png",
				[13] = "arquivos/10/camisa/padrao/13.png",
				[14] = "arquivos/10/camisa/padrao/14.png",
				[15] = "arquivos/10/camisa/padrao/15.png",
				[16] = "arquivos/10/camisa/padrao/16.png",
				[17] = "arquivos/10/camisa/padrao/17.png",
				[18] = "arquivos/10/camisa/padrao/18.png",
				[19] = "arquivos/10/camisa/padrao/19.png",
				[20] = "arquivos/10/camisa/padrao/20.png",
				[21] = "arquivos/10/camisa/padrao/21.png",
				[22] = "arquivos/10/camisa/padrao/22.png",
				[23] = "arquivos/10/camisa/padrao/23.png",
				[24] = "arquivos/10/camisa/padrao/24.png",
				[25] = "arquivos/10/camisa/padrao/25.png",
				[26] = "arquivos/10/camisa/padrao/26.png",
				[27] = "arquivos/10/camisa/padrao/27.png",
				[28] = "arquivos/10/camisa/padrao/28.png",
				[29] = "arquivos/10/camisa/padrao/29.png",
				[30] = "arquivos/10/camisa/padrao/30.png",
				[31] = "arquivos/10/camisa/padrao/31.png",
				[32] = "arquivos/10/camisa/padrao/32.png",
				[33] = "arquivos/10/camisa/padrao/33.png",
				[34] = "arquivos/10/camisa/padrao/34.png",
				[35] = "arquivos/10/camisa/padrao/35.png",
				[36] = "arquivos/10/camisa/padrao/36.png",
				[37] = "arquivos/10/camisa/padrao/37.png",
				[38] = "arquivos/10/camisa/padrao/38.png",
				[39] = "arquivos/10/camisa/padrao/39.png",
				[40] = "arquivos/10/camisa/padrao/40.png",
				[41] = "arquivos/10/camisa/padrao/41.png",
				[42] = "arquivos/10/camisa/padrao/42.png",
				[43] = "arquivos/10/camisa/padrao/43.png",
			},
			[4] = {
				[1] = "arquivos/PartesComum/camisa/casaco/1.png",
				[2] = "arquivos/PartesComum/camisa/casaco/2.png",
				[3] = "arquivos/PartesComum/camisa/casaco/3.png",
				[4] = "arquivos/PartesComum/camisa/casaco/4.png",
				[5] = "arquivos/PartesComum/camisa/casaco/5.png",
				[6] = "arquivos/PartesComum/camisa/casaco/6.png",
				[7] = "arquivos/PartesComum/camisa/casaco/7.png",
				[8] = "arquivos/PartesComum/camisa/casaco/8.png",	
				[9] = "arquivos/PartesComum/camisa/casaco/9.png",
				[10] = "arquivos/PartesComum/camisa/casaco/10.png",
				[11] = "arquivos/PartesComum/camisa/casaco/11.png",
				[12] = "arquivos/PartesComum/camisa/casaco/12.png",
				[13] = "arquivos/PartesComum/camisa/casaco/13.png",
				[14] = "arquivos/PartesComum/camisa/casaco/14.png",
				[15] = "arquivos/PartesComum/camisa/casaco/15.png",
				[16] = "arquivos/PartesComum/camisa/casaco/16.png",	
				[17] = "arquivos/PartesComum/camisa/casaco/17.png",
				[18] = "arquivos/PartesComum/camisa/casaco/18.png",
				[19] = "arquivos/PartesComum/camisa/casaco/19.png",
				[20] = "arquivos/PartesComum/camisa/casaco/20.png",
			},
		},
		["perna"] = {
			[1] = {
				[1] = "arquivos/10/camisa/padrao/1.png",
				[2] = "arquivos/10/camisa/padrao/3.png",
				[3] = "arquivos/10/camisa/padrao/6.png",
				[4] = "arquivos/10/camisa/padrao/7.png",
				[5] = "arquivos/10/camisa/padrao/10.png",
				[6] = "arquivos/10/camisa/padrao/12.png",
				[7] = "arquivos/10/camisa/padrao/13.png",
				[8] = "arquivos/10/camisa/padrao/15.png",
				[9] = "arquivos/10/camisa/padrao/18.png",
				[10] = "arquivos/10/perna/calcinha/3.png",
				[11] = "arquivos/10/camisa/padrao/22.png",
				[12] = "arquivos/10/camisa/padrao/25.png",
				[13] = "arquivos/10/camisa/padrao/27.png",
				[14] = "arquivos/10/camisa/padrao/29.png",
				[15] = "arquivos/10/perna/calcinha/4.png",
				[16] = "arquivos/10/perna/calcinha/5.png",
				[17] = "arquivos/10/perna/calcinha/6.png",
				[18] = "arquivos/10/perna/calcinha/7.png",
				[19] = "arquivos/10/camisa/padrao/39.png",
				[20] = "arquivos/10/camisa/padrao/41.png",
				[21] = "arquivos/10/perna/calcinha/8.png",
				[22] = "arquivos/10/perna/calcinha/1.png",
				[23] = "arquivos/10/perna/calcinha/2.png",

			},
			[2] = {
				[1] = "arquivos/10/perna/short/1.png",
				[2] = "arquivos/10/perna/short/2.png",
				[3] = "arquivos/10/perna/short/3.png",
				[4] = "arquivos/10/perna/short/4.png",
				[5] = "arquivos/10/perna/short/5.png",
				[6] = "arquivos/10/perna/short/6.png",
				[7] = "arquivos/10/perna/short/7.png",
				[8] = "arquivos/10/perna/short/8.png",
				[9] = "arquivos/10/perna/short/9.png",
				[10] = "arquivos/10/perna/short/10.png",
				[11] = "arquivos/10/perna/short/11.png",
			},
			[3] = {
				[1] = "arquivos/PartesComum/perna/calca/1.png",	
				[2] = "arquivos/PartesComum/perna/calca/2.png",
				[3] = "arquivos/PartesComum/perna/calca/3.png",
				[4] = "arquivos/PartesComum/perna/calca/4.png",
				[5] = "arquivos/PartesComum/perna/calca/5.png",
				[6] = "arquivos/PartesComum/perna/calca/6.png",	
				[7] = "arquivos/PartesComum/perna/calca/7.png",
				[8] = "arquivos/PartesComum/perna/calca/8.png",
				[9] = "arquivos/PartesComum/perna/calca/9.png",
				[10] = "arquivos/PartesComum/perna/calca/10.png",
				[11] = "arquivos/PartesComum/perna/calca/11.png",	
				[12] = "arquivos/PartesComum/perna/calca/12.png",	
			},
		},
		["sapato"] = {
			[1] = {
				[1] = "arquivos/PartesComum/sapato/sandalia/1.png",
				[2] = "arquivos/PartesComum/sapato/sandalia/2.png",
				[3] = "arquivos/PartesComum/sapato/sandalia/3.png",
				[4] = "arquivos/PartesComum/sapato/sandalia/4.png",
				[5] = "arquivos/PartesComum/sapato/sandalia/5.png",
				[6] = "arquivos/PartesComum/sapato/sandalia/6.png",
				[7] = "arquivos/PartesComum/sapato/sandalia/7.png",
				[8] = "arquivos/PartesComum/sapato/sandalia/8.png",
				[9] = "arquivos/PartesComum/sapato/sandalia/9.png",
			},
			[2] = {
				[1] = "arquivos/PartesComum/sapato/tubarao/1.png",
				[2] = "arquivos/PartesComum/sapato/tubarao/2.png",
				[3] = "arquivos/PartesComum/sapato/tubarao/3.png",
				[4] = "arquivos/PartesComum/sapato/tubarao/4.png",
				[5] = "arquivos/PartesComum/sapato/tubarao/5.png",
				[6] = "arquivos/PartesComum/sapato/tubarao/6.png",
			},
			[3] = {
				[1] = "arquivos/PartesComum/sapato/allStar/1.png",
				[2] = "arquivos/PartesComum/sapato/allStar/2.png",
				[3] = "arquivos/PartesComum/sapato/allStar/3.png",
				[4] = "arquivos/PartesComum/sapato/allStar/4.png",
				[5] = "arquivos/PartesComum/sapato/allStar/5.png",
				[6] = "arquivos/PartesComum/sapato/allStar/6.png",
				[7] = "arquivos/PartesComum/sapato/allStar/7.png",
				[8] = "arquivos/PartesComum/sapato/allStar/8.png",
				[9] = "arquivos/PartesComum/sapato/allStar/9.png",
			},
		},
		["oculos"] = {
			[1] = {
				[1] = "arquivos/PartesComum/oculos/xsquared/1.png",
				[2] = "arquivos/PartesComum/oculos/xsquared/2.png",
				[3] = "arquivos/PartesComum/oculos/xsquared/3.png",
				[4] = "arquivos/PartesComum/oculos/xsquared/4.png",
				[5] = "arquivos/PartesComum/oculos/xsquared/5.png",
				[6] = "arquivos/PartesComum/oculos/xsquared/6.png",
				[7] = "arquivos/PartesComum/oculos/xsquared/7.png",
				[8] = "arquivos/PartesComum/oculos/xsquared/8.png",
			},
			[2] = {
				[1] = "arquivos/PartesComum/oculos/juju/1.png",
				[2] = "arquivos/PartesComum/oculos/juju/2.png",
				[3] = "arquivos/PartesComum/oculos/juju/3.png",
				[4] = "arquivos/PartesComum/oculos/juju/4.png",
				[5] = "arquivos/PartesComum/oculos/juju/5.png",
				[6] = "arquivos/PartesComum/oculos/juju/6.png",
				[7] = "arquivos/PartesComum/oculos/juju/7.png",
				[8] = "arquivos/PartesComum/oculos/juju/8.png",
			},
		},
		["mochila"] = {
			[1] = {
				[1] = "arquivos/PartesComum/mochila/paraquedas/1.png",
				[2] = "arquivos/PartesComum/mochila/paraquedas/2.png",
				[3] = "arquivos/PartesComum/mochila/paraquedas/3.png",
				[4] = "arquivos/PartesComum/mochila/paraquedas/4.png",
				[5] = "arquivos/PartesComum/mochila/paraquedas/5.png",
				[6] = "arquivos/PartesComum/mochila/paraquedas/6.png",
				[7] = "arquivos/PartesComum/mochila/paraquedas/7.png",
				[8] = "arquivos/PartesComum/mochila/paraquedas/8.png",
				[9] = "arquivos/PartesComum/mochila/paraquedas/9.png",
				[10] = "arquivos/PartesComum/mochila/paraquedas/10.png",
				[11] = "arquivos/PartesComum/mochila/paraquedas/11.png",
				[12] = "arquivos/PartesComum/mochila/paraquedas/12.png",
				[13] = "arquivos/PartesComum/mochila/paraquedas/13.png",
				[14] = "arquivos/PartesComum/mochila/paraquedas/14.png",
			},
		},
		["mascara"] = {			
			[1] = {
				[1] = "arquivos/PartesComum/mascara/padrao/1.png",
				[2] = "arquivos/PartesComum/mascara/padrao/2.png",
				[3] = "arquivos/PartesComum/mascara/padrao/3.png",
				[4] = "arquivos/PartesComum/mascara/padrao/4.png",
				[5] = "arquivos/PartesComum/mascara/padrao/5.png",
				[6] = "arquivos/PartesComum/mascara/padrao/6.png",
				[7] = "arquivos/PartesComum/mascara/padrao/7.png",
				[8] = "arquivos/PartesComum/mascara/padrao/8.png",
				[9] = "arquivos/PartesComum/mascara/padrao/9.png",
			},
			[2] = {
				[1] = "arquivos/PartesComum/mascara/bandana/1.png",
				[2] = "arquivos/PartesComum/mascara/bandana/2.png",
				[3] = "arquivos/PartesComum/mascara/bandana/3.png",
				[4] = "arquivos/PartesComum/mascara/bandana/4.png",
				[5] = "arquivos/PartesComum/mascara/bandana/5.png",
				[6] = "arquivos/PartesComum/mascara/bandana/6.png",
				[7] = "arquivos/PartesComum/mascara/bandana/7.png",
				[8] = "arquivos/PartesComum/mascara/bandana/8.png",
				[9] = "arquivos/PartesComum/mascara/bandana/9.png",
			},
		},
		["pernaparte"] = {			
			[1] = {
				[0] = "arquivos/10/texturaPele/perna/1/padrao.png",
				[1] = "arquivos/10/texturaPele/perna/1/padrao.png",
				[2] = "arquivos/10/texturaPele/perna/1/padrao.png",
				[3] = "arquivos/10/texturaPele/perna/1/calca.png",
			},
			[2] = {
				[0] = "arquivos/10/texturaPele/perna/2/padrao.png",
				[1] = "arquivos/10/texturaPele/perna/2/padrao.png",
				[2] = "arquivos/10/texturaPele/perna/2/padrao.png",
				[3] = "arquivos/10/texturaPele/perna/2/calca.png",
			},
			[3] = {
				[0] = "arquivos/10/texturaPele/perna/3/padrao.png",
				[1] = "arquivos/10/texturaPele/perna/3/padrao.png",
				[2] = "arquivos/10/texturaPele/perna/3/padrao.png",
				[3] = "arquivos/10/texturaPele/perna/3/calca.png",
			},
		},
		["pele"] = {			
			[1] = {
				[0] = "arquivos/10/texturaPele/corpo/1/padrao.png",
				[1] = "arquivos/10/texturaPele/corpo/1/padrao.png",
				[2] = "arquivos/10/texturaPele/corpo/1/top3.png",
				[3] = "arquivos/10/texturaPele/corpo/1/top2.png",
				[4] = "arquivos/10/texturaPele/corpo/1/casaco.png",
			},
			[2] = {
				[0] = "arquivos/10/texturaPele/corpo/2/padrao.png",
				[1] = "arquivos/10/texturaPele/corpo/2/padrao.png",
				[2] = "arquivos/10/texturaPele/corpo/2/top3.png",
				[3] = "arquivos/10/texturaPele/corpo/2/top2.png",
				[4] = "arquivos/10/texturaPele/corpo/2/casaco.png",
			},
			[3] = {
				[0] = "arquivos/10/texturaPele/corpo/3/padrao.png",
				[1] = "arquivos/10/texturaPele/corpo/3/padrao.png",
				[2] = "arquivos/10/texturaPele/corpo/3/top3.png",
				[3] = "arquivos/10/texturaPele/corpo/3/top2.png",
				[4] = "arquivos/10/texturaPele/corpo/3/casaco.png",
			},
		},
		["face"] = {			
			[1] = {
				[1] = "arquivos/10/texturaPele/face/1/padrao.png",
				[2] = "arquivos/10/texturaPele/face/1/1.png",
				[3] = "arquivos/10/texturaPele/face/1/2.png",
				[4] = "arquivos/10/texturaPele/face/1/3.png",
				[5] = "arquivos/10/texturaPele/face/1/4.png",
				[6] = "arquivos/10/texturaPele/face/1/5.png",
				[7] = "arquivos/10/texturaPele/face/1/6.png",
				[8] = "arquivos/10/texturaPele/face/1/7.png",
			},
			[2] = {
				[1] = "arquivos/10/texturaPele/face/2/padrao.png",
				[2] = "arquivos/10/texturaPele/face/2/1.png",
				[3] = "arquivos/10/texturaPele/face/2/2.png",
				[4] = "arquivos/10/texturaPele/face/2/3.png",
				[5] = "arquivos/10/texturaPele/face/2/4.png",
				[6] = "arquivos/10/texturaPele/face/2/5.png",
				[7] = "arquivos/10/texturaPele/face/2/6.png",
				[8] = "arquivos/10/texturaPele/face/2/7.png",
			},
			[3] = {
				[1] = "arquivos/10/texturaPele/face/3/padrao.png",
				[2] = "arquivos/10/texturaPele/face/3/1.png",
				[3] = "arquivos/10/texturaPele/face/3/2.png",
				[4] = "arquivos/10/texturaPele/face/3/3.png",
				[5] = "arquivos/10/texturaPele/face/3/4.png",
				[6] = "arquivos/10/texturaPele/face/3/5.png",
				[7] = "arquivos/10/texturaPele/face/3/6.png",
				[8] = "arquivos/10/texturaPele/face/3/7.png",
			},
		},
		["pe"] = {			
			[1] = {
				[0] = "arquivos/10/texturaPele/pe/1/padrao.png",
				[1] = "arquivos/10/texturaPele/pe/1/padrao.png",
				[2] = "arquivos/10/texturaPele/pe/1/sapato.png",
				[3] = "arquivos/10/texturaPele/pe/1/sapato.png",
			},
			[2] = {
				[0] = "arquivos/10/texturaPele/pe/2/padrao.png",
				[1] = "arquivos/10/texturaPele/pe/2/padrao.png",
				[2] = "arquivos/10/texturaPele/pe/2/sapato.png",
				[3] = "arquivos/10/texturaPele/pe/2/sapato.png",
			},
			[3] = {
				[0] = "arquivos/10/texturaPele/pe/3/padrao.png",
				[1] = "arquivos/10/texturaPele/pe/3/padrao.png",
				[2] = "arquivos/10/texturaPele/pe/3/sapato.png",
				[3] = "arquivos/10/texturaPele/pe/3/sapato.png",
			},
		},
	},
}


